### ISSUE TITLE
Doesn't work with recordsize change

### ISSUE THREAD

**Issue by bdrewery** [pjd/filerewrite#2]
I'm not familiar with ZFS internals to know why but it can be seen with stat(1).

On a dataset I had `recordsize=128k`. Changed to `recordsize=1M`.
```
# stat -f %k ./node-v16.10.0.tar.gz
131072
# filerewrite ./node-v16.10.0.tar.gz
# stat -f %k ./node-v16.10.0.tar.gz
131072
# cp ./node-v16.10.0.tar.gz ./node-v16.10.0.tar.gz2
# stat -f %k ./node-v16.10.0.tar.gz ./node-v16.10.0.tar.gz2
131072
1048576
```

**Comment by pjd** [comment]
Correct. Once there are two block in the file, the block size cannot change. We would need to copy the data into a temporary file and do rename(2).
